<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnCart</name>
   <tag></tag>
   <elementGuidId>fbd12fdf-5773-4475-8ef2-64bfa5d68974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon_bag_alt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-cart']/a/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bc6ff3b7-5cc6-4540-a4a9-37053ad5ddb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_bag_alt</value>
      <webElementGuid>ce0a97cf-3f15-4889-a4ef-4c360dd80f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-cart&quot;)/a[@class=&quot;cart-button&quot;]/span[@class=&quot;cart-item has-items&quot;]/i[@class=&quot;icon_bag_alt&quot;]</value>
      <webElementGuid>91f5b7b5-1620-447b-bd8f-0316309bed41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-cart']/a/span/i</value>
      <webElementGuid>6915101e-4846-4833-ba60-acea96e6f516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
      <webElementGuid>2b562b61-e32e-4ec1-a8a7-711f169a312c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
