<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnPlaceOrder</name>
   <tag></tag>
   <elementGuidId>8ef61042-92c9-4d76-848b-ae5c0634ce22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#place_order</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='place_order']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>852bafe4-07f9-429c-a350-3608e45196ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>11700103-eb76-48cf-b8b6-5a9d7e7df2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button alt</value>
      <webElementGuid>185e09f2-7cfa-43ab-9fb8-357af26cfad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>woocommerce_checkout_place_order</value>
      <webElementGuid>607141cf-a1c3-49e9-9302-23c4dfa37153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>place_order</value>
      <webElementGuid>3f5369c1-2df9-4267-a076-15f16b17d2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Place order</value>
      <webElementGuid>5e11547a-3bb5-4c11-a5a4-0bce518d55f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Place order</value>
      <webElementGuid>6bf3fbb6-998a-46b5-8317-6c23ec5d1eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Place order</value>
      <webElementGuid>b4f0a957-9ab0-4c3a-8e1f-6a3caafca890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;place_order&quot;)</value>
      <webElementGuid>e0123ea6-0f65-45c1-b3fd-56ebf4bc3cf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='place_order']</value>
      <webElementGuid>7eb57728-86ad-41c3-a75e-b553e44097bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/div/button</value>
      <webElementGuid>c00c57e7-d526-40b6-9cd3-700f7ced77e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::button[1]</value>
      <webElementGuid>eeac12cf-1419-45e4-b53f-d760b46f4b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='terms and conditions'])[1]/following::button[1]</value>
      <webElementGuid>2cfe83e3-0d8f-4af2-9591-67873d753851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='opening time'])[1]/preceding::button[1]</value>
      <webElementGuid>7b415629-e961-4f47-a443-16911a308ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon - Fri: 8AM - 10PM'])[1]/preceding::button[1]</value>
      <webElementGuid>2cbc6b40-a1e9-488d-9469-c4c4427221b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Place order']/parent::*</value>
      <webElementGuid>14a54be5-6a5d-47bb-96c2-e022d3db3be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/button</value>
      <webElementGuid>60350d72-6e16-420c-833d-9759a07e5324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'woocommerce_checkout_place_order' and @id = 'place_order' and (text() = 'Place order' or . = 'Place order')]</value>
      <webElementGuid>79a0065b-cad3-49d6-a48c-fc3c85422ac4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
