<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdownCountry</name>
   <tag></tag>
   <elementGuidId>f5b91038-bfa1-4d61-bb64-69c7e1d8cc08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-billing_country-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-billing_country-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cfd4f6f7-52e2-40a0-acff-b73ef6ffc604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>a9dc7d8a-3d40-4715-84d3-c9998809ffa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-billing_country-container</value>
      <webElementGuid>d9e2b4bc-9ef6-4978-b065-ceefe9aee0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>f55406e9-7761-4cec-b37f-2e86ab72a598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9d656da3-dc61-4655-a5aa-9db192aa769a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Indonesia</value>
      <webElementGuid>73c9f44d-4ce6-4673-9719-080461082932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia</value>
      <webElementGuid>42022dd9-9f0b-4cad-855b-32ad5cc6baec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-billing_country-container&quot;)</value>
      <webElementGuid>4866278d-10fa-43cd-806f-4f201e9291ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-billing_country-container']</value>
      <webElementGuid>b322b471-1113-4962-9515-f5dec6a35f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_country_field']/span/span/span/span/span</value>
      <webElementGuid>341bef00-7e17-488d-a41e-4c57c2fbb52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[5]</value>
      <webElementGuid>980ad531-9f1f-40bf-9e37-a2ebcabf828b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::span[3]</value>
      <webElementGuid>32357a1e-7257-4877-92ec-1d86185cd2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span/span</value>
      <webElementGuid>5a6fa286-572f-4aa2-b062-b1b619487a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-billing_country-container' and @title = 'Indonesia' and (text() = 'Indonesia' or . = 'Indonesia')]</value>
      <webElementGuid>b74e55af-a285-403b-bc5f-9e22eb562292</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
