<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>thankYouLetter</name>
   <tag></tag>
   <elementGuidId>d33214a5-e3d1-4858-b0eb-70da3c71db9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[@class='woocommerce-thankyou-order-received']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[@class='woocommerce-thankyou-order-received']</value>
      <webElementGuid>8a15affe-1075-4373-b171-f31a041c6baf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
