<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtEmail</name>
   <tag></tag>
   <elementGuidId>db65dd05-dd78-4749-a7bd-a5a0864042c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fdf19bc-259e-470c-854b-3073768043f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>fdbf991b-dfc0-4b34-a287-da3ecd93956b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>dcd309a1-d401-49c5-8325-139d64ce1d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_email</value>
      <webElementGuid>83cd0778-5e5c-40ba-985c-a699ee6ed912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_email</value>
      <webElementGuid>93005d2c-d050-4104-8c38-791055016723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>juli@gmail.com</value>
      <webElementGuid>99139ce1-9f42-4566-bcad-22060cddfd06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ab1a6792-17e4-4cf0-a7e0-f23d7c681cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_email&quot;)</value>
      <webElementGuid>f19c5316-a346-475f-96b2-ad6502a216eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_email']</value>
      <webElementGuid>322b0146-e36e-46f3-9dbf-5937c20c9425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_email_field']/span/input</value>
      <webElementGuid>0bf9a579-b942-49aa-8da4-a9c5665a3320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[11]/span/input</value>
      <webElementGuid>5db28cd6-e213-4485-8016-20f5b72953fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'billing_email' and @id = 'billing_email']</value>
      <webElementGuid>7684d0fc-6e63-467e-9f88-a9e7535f3021</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
