<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnRegister</name>
   <tag></tag>
   <elementGuidId>1f07feb5-08a5-4ba6-9091-61248f2774d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@name='register']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@name='register']</value>
      <webElementGuid>4eced4d6-296b-4417-a16a-9373e023d520</webElementGuid>
   </webElementProperties>
</WebElementEntity>
