<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>loginPassword</name>
   <tag></tag>
   <elementGuidId>d3923abd-b660-45bf-831c-984fe4b7bd3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='user_pass']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='user_pass']</value>
      <webElementGuid>b77d5f8a-141c-4350-bc15-cac0229a5b2f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
