<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>loginUsername</name>
   <tag></tag>
   <elementGuidId>69c5f24e-06e8-4945-a720-c68d64a51ccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='user_login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='user_login']</value>
      <webElementGuid>770a65c8-729d-4f86-924d-80b9189e33df</webElementGuid>
   </webElementProperties>
</WebElementEntity>
